services:

  HeimrichHannot\FieldpaletteBundle\:
    resource: '../../{Dca,Registry}/*'
    autowire: true
    autoconfigure: true

  HeimrichHannot\FieldpaletteBundle\EventListener\Contao\:
    resource: '../../EventListener/Contao/*'
    autowire: true
    autoconfigure: true
    public: true

  HeimrichHannot\FieldpaletteBundle\EventListener\CallbackListener:
    autowire: true
    autoconfigure: true
    public: true

  huh.fieldpalette.listener.callback:
    alias: HeimrichHannot\FieldpaletteBundle\EventListener\CallbackListener
    public: true
    deprecated: The "%alias_id%" service is deprecated since heimrichhannot/contao-fieldpalette-bundle 0.6.12 and will be removed in 1.0.

  huh.fieldpalette.element.button:
    class: HeimrichHannot\FieldpaletteBundle\Element\ButtonElement
    public: true
    arguments:
      - '@contao.framework'
      - '%huh.fieldpalette.table%'
      - '@twig'
      - '@huh.utils.routing'
      - '@huh.fieldpalette.dca.handler'
  huh.fieldpalette.manager:
    class: HeimrichHannot\FieldpaletteBundle\Manager\FieldPaletteModelManager
    public: true
  huh.fieldpalette.dca.extractor:
    class: HeimrichHannot\FieldpaletteBundle\DcaHelper\DcaExtractor
    arguments: ['@service_container']
  huh.fieldpalette.dca.handler:
    class: HeimrichHannot\FieldpaletteBundle\DcaHelper\DcaHandler
    public: true
    arguments:
      - '%huh.fieldpalette.table%'
      - '@contao.framework'
      - '@huh.fieldpalette.manager'
      - '@request_stack'
      - '@HeimrichHannot\FieldpaletteBundle\Registry\FieldPaletteRegistry'

  # Symfony 4 autowire convention fix (ambiguous namespace alias)
  HeimrichHannot\FieldpaletteBundle\Manager\FieldPaletteModelManager: '@huh.fieldpalette.manager'
  HeimrichHannot\FieldpaletteBundle\DcaHelper\DcaHandler: '@huh.fieldpalette.dca.handler'