services:

  HeimrichHannot\FieldpaletteBundle\:
    resource: '../../{Dca,Util}/*'
    autowire: true

  HeimrichHannot\FieldpaletteBundle\DcaHelper\DcaExtractor:
    autowire: true
    autoconfigure: true
    public: true
    bind:
      $fieldPaletteTable: '%huh.fieldpalette.table%'

  HeimrichHannot\FieldpaletteBundle\Util\FormUtilPolyfill:
    autowire: true
    autoconfigure: true
    public: true
    bind:
      $kernelBundles: '%kernel.bundles%'

  HeimrichHannot\FieldpaletteBundle\EventListener\Contao\:
    resource: '../../EventListener/Contao/*'
    autowire: true
    public: true

  HeimrichHannot\FieldpaletteBundle\EventListener\CallbackListener:
    autowire: true
    autoconfigure: true
    public: true

  huh.fieldpalette.listener.callback:
    alias: HeimrichHannot\FieldpaletteBundle\EventListener\CallbackListener
    public: true
    deprecated:
      version: 0.6.12
      package: heimrichhannot/contao-fieldpalette-bundle
      message: The "%alias_id%" service is deprecated since heimrichhannot/contao-fieldpalette-bundle 0.6.12 and will be removed in 1.0.

  huh.fieldpalette.element.button:
    class: HeimrichHannot\FieldpaletteBundle\Element\ButtonElement
    public: true
    arguments:
      - '@contao.framework'
      - '%huh.fieldpalette.table%'
      - '@twig'
      # - '@huh.utils.routing'
      - '@huh.fieldpalette.dca.handler'
  huh.fieldpalette.registry:
    class: HeimrichHannot\FieldpaletteBundle\Registry\FieldPaletteRegistry
  huh.fieldpalette.manager:
    class: HeimrichHannot\FieldpaletteBundle\Manager\FieldPaletteModelManager
    public: true
  huh.fieldpalette.dca.extractor:
    class: HeimrichHannot\FieldpaletteBundle\DcaHelper\DcaExtractor
  huh.fieldpalette.dca.handler:
    class: HeimrichHannot\FieldpaletteBundle\DcaHelper\DcaHandler
    public: true
    arguments:
      - '%huh.fieldpalette.table%'
      - '@contao.framework'
      - '@huh.fieldpalette.manager'
      - '@request_stack'
      - '@huh.fieldpalette.registry'

  # Symfony 4 autowire convention fix (ambiguous namespace alias)
  HeimrichHannot\FieldpaletteBundle\Manager\FieldPaletteModelManager: '@huh.fieldpalette.manager'
  HeimrichHannot\FieldpaletteBundle\DcaHelper\DcaHandler: '@huh.fieldpalette.dca.handler'
  HeimrichHannot\FieldpaletteBundle\Registry\FieldPaletteRegistry: '@huh.fieldpalette.registry'