services:

  HeimrichHannot\FieldpaletteBundle\:
    resource: '../../{Dca,Registry,EventListener}/*'
    autowire: true
    autoconfigure: true
    public: true

  huh.fieldpalette.element.button:
    class: HeimrichHannot\FieldpaletteBundle\Element\ButtonElement
    public: true
    arguments:
      - '@contao.framework'
      - '%huh.fieldpalette.table%'
      - '@twig'
      - '@huh.utils.routing'
      - '@huh.fieldpalette.dca.handler'
  huh.fieldpalette.manager:
    class: HeimrichHannot\FieldpaletteBundle\Manager\FieldPaletteModelManager
    public: true
  huh.fieldpalette.dca.extractor:
    class: HeimrichHannot\FieldpaletteBundle\DcaHelper\DcaExtractor
    arguments: ['@service_container']
  huh.fieldpalette.dca.handler:
    class: HeimrichHannot\FieldpaletteBundle\DcaHelper\DcaHandler
    public: true
    arguments:
      - '%huh.fieldpalette.table%'
      - '@contao.framework'
      - '@huh.fieldpalette.manager'
      - '@request_stack'
      - '@HeimrichHannot\FieldpaletteBundle\Registry\FieldPaletteRegistry'

  # Symfony 4 autowire convention fix (ambiguous namespace alias)
  HeimrichHannot\FieldpaletteBundle\Manager\FieldPaletteModelManager: '@huh.fieldpalette.manager'
  HeimrichHannot\FieldpaletteBundle\DcaHelper\DcaHandler: '@huh.fieldpalette.dca.handler'