parameters:
  huh.fieldpalette.table: tl_fieldpalette

services:
  huh.fieldpalette.listener.hook:
    class: HeimrichHannot\FieldpaletteBundle\EventListener\HookListener
    arguments:
      - '@huh.fieldpalette.dca.extractor'
      - '@service_container'
      - '@contao.framework'
      - '@huh.fieldpalette.dca.handler'
      - '@huh.fieldpalette.manager'
  huh.fieldpalette.listener.callback:
    class: HeimrichHannot\FieldpaletteBundle\EventListener\CallbackListener
    arguments:
       - '@contao.framework'
       - '@huh.fieldpalette.manager'
       - '@huh.fieldpalette.dca.handler'
       - '@request_stack'
       - '@huh.utils.container'
       - '@huh.utils.url'
       - '@huh.utils.routing'
       - '@monolog.logger.contao'
  huh.fieldpalette.element.button:
    class: HeimrichHannot\FieldpaletteBundle\Element\ButtonElement
    arguments:
      - '@contao.framework'
      - '%huh.fieldpalette.table%'
      - '@twig'
      - '@huh.utils.routing'
      - '@huh.fieldpalette.dca.handler'
  huh.fieldpalette.registry:
    class: HeimrichHannot\FieldpaletteBundle\Registry\FieldPaletteRegistry
  huh.fieldpalette.manager:
    class: HeimrichHannot\FieldpaletteBundle\Manager\FieldPaletteModelManager
  huh.fieldpalette.dca.extractor:
    class: HeimrichHannot\FieldpaletteBundle\DcaHelper\DcaExtractor
    arguments: ['@service_container']
  huh.fieldpalette.dca.handler:
    class: HeimrichHannot\FieldpaletteBundle\DcaHelper\DcaHandler
    arguments:
      - '%huh.fieldpalette.table%'
      - '@contao.framework'
      - '@huh.fieldpalette.manager'
      - '@request_stack'
      - '@huh.fieldpalette.registry'